Repository FiT-8-plus-1-BiT/backend, pull requests merged in 2025-04, with the labels that each got.

#131 [#4] 네이버 점검으로 인한 개발용 카카오 오픈
  src/main/java/eightplusone/bit/fit/domain/auth/handler/CustomOAuth2SuccessHandler.java
Labels: 🎨refactor

#132 [#130] 최근 메시지 조회 API 수정
  src/main/java/eightplusone/bit/fit/domain/chat/controller/ChatController.java
  src/main/java/eightplusone/bit/fit/domain/chat/dto/ChatMessageDto.java
  src/main/java/eightplusone/bit/fit/domain/chat/service/ChatService.java
  src/test/java/eightplusone/bit/fit/domain/chat/service/ChatServiceTest.java
Labels: 🎨refactor, 🔨fix

#133 chore: 네이버 점검으로 인한 개발용 카카오 에러 리다이렉트 #4
  src/main/java/eightplusone/bit/fit/domain/auth/handler/CustomOAuth2AuthenticationFailureHandler.java
Labels: 🎨refactor

#135 [#4] 서버 상태 확인용 컨트롤러 추가
  src/main/java/eightplusone/bit/fit/domain/auth/handler/CustomOAuth2AuthenticationFailureHandler.java
  src/main/java/eightplusone/bit/fit/domain/auth/handler/CustomOAuth2SuccessHandler.java
  src/main/java/eightplusone/bit/fit/domain/auth/interceptor/WebSocketInterceptor.java
  src/main/java/eightplusone/bit/fit/global/controller/HealthCheckController.java
  src/main/java/eightplusone/bit/fit/global/enums/ApiEndpoint.java
Labels: ✨ feat
