Repository FiT-8-plus-1-BiT/backend, pull requests merged in 2025-03, with the labels that each got.

#3 [#1] 음성 1:N 브로드캐스팅 기능
  build.gradle
  src/main/java/eightplusone/bit/fit/global/config/AudioWebSocketConfig.java
  src/main/java/eightplusone/bit/fit/global/websocket/CallHandler.java
  src/main/java/eightplusone/bit/fit/global/websocket/UserSession.java
Labels: ✨ feat

#6 [#5] websocket&redis config
  build.gradle
  src/main/java/eightplusone/bit/fit/global/config/RedisConfig.java
  src/main/java/eightplusone/bit/fit/global/config/WebSocketConfig.java
Labels: ⚙ build, ✨ feat

#11 [#4] 소셜 로그인 사전 작업
  build.gradle
  src/main/java/eightplusone/bit/fit/domain/auth/dto/CustomOAuth2User.java
  src/main/java/eightplusone/bit/fit/domain/auth/dto/OAuth2UserDto.java
  src/main/java/eightplusone/bit/fit/domain/auth/enums/Role.java
  src/main/java/eightplusone/bit/fit/domain/auth/service/RedisTokenService.java
  src/main/java/eightplusone/bit/fit/domain/user/entity/User.java
  src/main/java/eightplusone/bit/fit/domain/user/repository/UserRepository.java
  src/main/java/eightplusone/bit/fit/global/base/BaseTimeEntity.java
  src/main/java/eightplusone/bit/fit/global/utils/CookieUtil.java
  src/test/java/eightplusone/bit/fit/domain/auth/service/RedisTokenServiceTest.java
  src/test/java/eightplusone/bit/fit/global/utils/CookieUtilTest.java
Labels: ⚙ build, ✨ feat, 💡test

#12 [#2] multi room 1:N audio streaming으로 확장 구현
  src/main/java/eightplusone/bit/fit/domain/streaming/Room.java
  src/main/java/eightplusone/bit/fit/domain/streaming/RoomManager.java
  src/main/java/eightplusone/bit/fit/global/config/AudioWebSocketConfig.java
  src/main/java/eightplusone/bit/fit/global/websocket/CallHandler.java
  src/main/java/eightplusone/bit/fit/global/websocket/UserSession.java
Labels: ✨ feat

#14 [#13] pr, push 시 빌드(+테스트) CI 작업 설정.
  .github/ISSUE_TEMPLATE/workflows/build-check.yml
Labels: ✅ ci/cd

#15 [#4] 소셜 로그인 기능
  src/main/java/eightplusone/bit/fit/domain/auth/dto/CustomUserDetails.java
  src/main/java/eightplusone/bit/fit/domain/auth/dto/GoogleResponse.java
  src/main/java/eightplusone/bit/fit/domain/auth/dto/KakaoResponse.java
  src/main/java/eightplusone/bit/fit/domain/auth/dto/NaverResponse.java
  src/main/java/eightplusone/bit/fit/domain/auth/dto/OAuth2Response.java
  src/main/java/eightplusone/bit/fit/domain/auth/filter/JwtAuthenticationFilter.java
  src/main/java/eightplusone/bit/fit/domain/auth/handler/CustomOAuth2SuccessHandler.java
  src/main/java/eightplusone/bit/fit/domain/auth/jwt/TokenProvider.java
  src/main/java/eightplusone/bit/fit/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/eightplusone/bit/fit/domain/auth/service/CustomUserDetailsService.java
  src/main/java/eightplusone/bit/fit/domain/auth/service/RedisTokenService.java
  src/main/java/eightplusone/bit/fit/domain/user/entity/User.java
  src/main/java/eightplusone/bit/fit/domain/user/repository/UserRepository.java
  src/main/java/eightplusone/bit/fit/global/config/SecurityConfig.java
  src/main/java/eightplusone/bit/fit/global/constants/CorsConstant.java
  src/main/java/eightplusone/bit/fit/global/constants/TokenConstant.java
  src/test/java/eightplusone/bit/fit/domain/auth/jwt/TokenProviderTest.java
  src/test/java/eightplusone/bit/fit/support/UserFixture.java
Labels: ✨ feat, 💡test

#19 [#4] 소셜로그인 부가 기능 구현
  src/main/java/eightplusone/bit/fit/domain/auth/controller/AuthController.java
  src/main/java/eightplusone/bit/fit/domain/auth/filter/CustomLogoutFilter.java
  src/main/java/eightplusone/bit/fit/domain/auth/filter/JwtAuthenticationFilter.java
  src/main/java/eightplusone/bit/fit/domain/auth/handler/CustomAccessDeniedHandler.java
  src/main/java/eightplusone/bit/fit/domain/auth/handler/CustomAuthenticationEntryPoint.java
  src/main/java/eightplusone/bit/fit/domain/auth/handler/CustomOAuth2AuthenticationFailureHandler.java
  src/main/java/eightplusone/bit/fit/domain/auth/handler/CustomOAuth2SuccessHandler.java
  src/main/java/eightplusone/bit/fit/domain/auth/service/OAuth2UnlinkService.java
  src/main/java/eightplusone/bit/fit/domain/user/controller/UserController.java
  src/main/java/eightplusone/bit/fit/domain/user/service/UserService.java
  src/main/java/eightplusone/bit/fit/global/config/SecurityConfig.java
  src/main/java/eightplusone/bit/fit/global/constants/CorsConstant.java
  src/main/java/eightplusone/bit/fit/global/enums/ApiEndpoint.java
  src/main/java/eightplusone/bit/fit/global/utils/CookieUtil.java
  src/test/java/eightplusone/bit/fit/domain/auth/controller/AuthControllerTest.java
  src/test/java/eightplusone/bit/fit/domain/auth/jwt/TokenProviderTest.java
  src/test/java/eightplusone/bit/fit/domain/user/service/UserServiceTest.java
  src/test/java/eightplusone/bit/fit/global/utils/CookieUtilTest.java
  src/test/java/eightplusone/bit/fit/support/annotation/WithMockCustom.java
  src/test/java/eightplusone/bit/fit/support/fixture/UserFixture.java
  src/test/java/eightplusone/bit/fit/support/security/MockCustomUserSecurityContextFactory.java
Labels: ✨ feat, 💡test

#21 [#20] 음성 스트링밍 인증 기능
  src/main/java/eightplusone/bit/fit/domain/auth/filter/JwtAuthenticationFilter.java
  src/main/java/eightplusone/bit/fit/global/config/AudioWebSocketConfig.java
  src/main/java/eightplusone/bit/fit/global/enums/ApiEndpoint.java
  src/main/java/eightplusone/bit/fit/global/websocket/CallHandler.java
Labels: ✨ feat

#25 [#24] 음성 스트리밍 혼잡도 분석 기능 호출
  src/main/java/eightplusone/bit/fit/domain/session/controller/SessionController.java
  src/main/java/eightplusone/bit/fit/domain/session/controller/SessionWebSocketController.java
  src/main/java/eightplusone/bit/fit/domain/session/entity/Session.java
  src/main/java/eightplusone/bit/fit/domain/session/repository/SessionRepository.java
  src/main/java/eightplusone/bit/fit/domain/session/service/SessionService.java
  src/main/java/eightplusone/bit/fit/domain/streaming/Room.java
  src/main/java/eightplusone/bit/fit/domain/streaming/RoomManager.java
  src/main/java/eightplusone/bit/fit/global/enums/ApiEndpoint.java
  src/main/java/eightplusone/bit/fit/global/websocket/CallHandler.java
  src/test/java/eightplusone/bit/fit/domain/session/service/SessionServiceTest.java
Labels: ✨ feat

#30 [#29] 공용 응답 및 에러핸들러 추가
  build.gradle
  src/main/java/eightplusone/bit/fit/domain/auth/controller/AuthController.java
  src/main/java/eightplusone/bit/fit/domain/auth/filter/CustomLogoutFilter.java
  src/main/java/eightplusone/bit/fit/domain/auth/filter/JwtAuthenticationFilter.java
  src/main/java/eightplusone/bit/fit/domain/auth/handler/CustomAccessDeniedHandler.java
  src/main/java/eightplusone/bit/fit/domain/auth/handler/CustomAuthenticationEntryPoint.java
  src/main/java/eightplusone/bit/fit/domain/auth/jwt/TokenProvider.java
  src/main/java/eightplusone/bit/fit/domain/auth/service/OAuth2UnlinkService.java
  src/main/java/eightplusone/bit/fit/domain/user/controller/UserController.java
  src/main/java/eightplusone/bit/fit/global/config/SecurityConfig.java
  src/main/java/eightplusone/bit/fit/global/dto/ResponseDto.java
  src/main/java/eightplusone/bit/fit/global/exception/CustomException.java
  src/main/java/eightplusone/bit/fit/global/exception/CustomExceptionHandler.java
  src/main/java/eightplusone/bit/fit/global/exception/ErrorCode.java
  src/main/java/eightplusone/bit/fit/global/utils/CookieUtil.java
  src/test/java/eightplusone/bit/fit/domain/auth/jwt/TokenProviderTest.java
  src/test/java/eightplusone/bit/fit/global/utils/CookieUtilTest.java
Labels: ✨ feat

#32 [#4] cors 포트 변경
  src/main/java/eightplusone/bit/fit/global/config/SecurityConfig.java
Labels: 🔨fix

#33 [#8] 채팅 API
  src/main/java/eightplusone/bit/fit/domain/auth/filter/JwtAuthenticationFilter.java
  src/main/java/eightplusone/bit/fit/domain/chat/controller/ChatController.java
  src/main/java/eightplusone/bit/fit/domain/chat/dto/ChatMessageDto.java
  src/main/java/eightplusone/bit/fit/domain/chat/entity/ChatMessage.java
  src/main/java/eightplusone/bit/fit/domain/chat/enums/ChatCategory.java
  src/main/java/eightplusone/bit/fit/domain/chat/repository/ChatRepository.java
  src/main/java/eightplusone/bit/fit/domain/chat/service/ChatService.java
  src/main/java/eightplusone/bit/fit/domain/user/repository/UserRedisRepository.java
  src/main/java/eightplusone/bit/fit/global/config/RedisConfig.java
  src/main/java/eightplusone/bit/fit/global/config/WebSocketConfig.java
  src/main/java/eightplusone/bit/fit/global/pubsub/ChatSubscriber.java
  src/main/java/eightplusone/bit/fit/global/pubsub/RedisMessagePublisher.java
  src/main/java/eightplusone/bit/fit/global/pubsub/RedisMessageSubscriber.java
  src/main/java/eightplusone/bit/fit/global/websocket/WebSocketEventListener.java
Labels: ✨ feat, 🔨fix

#34 [#31] 채팅 권한 인증 기능
  build.gradle
  src/main/java/eightplusone/bit/fit/domain/auth/interceptor/WebSocketInterceptor.java
  src/main/java/eightplusone/bit/fit/global/config/WebSocketConfig.java
  src/main/java/eightplusone/bit/fit/global/enums/ApiEndpoint.java
Labels: ✨ feat

#38 [#10] 좋아요 API 추가 및 ChatServiceTest 작성
  src/main/java/eightplusone/bit/fit/domain/chat/controller/ChatController.java
  src/main/java/eightplusone/bit/fit/domain/chat/dto/ChatMessageDto.java
  src/main/java/eightplusone/bit/fit/domain/chat/repository/ChatLikeRepository.java
  src/main/java/eightplusone/bit/fit/domain/chat/repository/ChatRepository.java
  src/main/java/eightplusone/bit/fit/domain/chat/service/ChatService.java
  src/main/java/eightplusone/bit/fit/global/exception/ErrorCode.java
  src/test/java/eightplusone/bit/fit/domain/chat/service/ChatServiceTest.java
Labels: ✨ feat, 💡test

#44 [#35] 쿠키 설정 변경
  src/main/java/eightplusone/bit/fit/global/config/SecurityConfig.java
  src/main/java/eightplusone/bit/fit/global/utils/CookieUtil.java
  src/test/java/eightplusone/bit/fit/domain/auth/controller/AuthControllerTest.java
  src/test/java/eightplusone/bit/fit/global/utils/CookieUtilTest.java
Labels: 🎨refactor

#46 [#43] endpoint 수정
  src/main/java/eightplusone/bit/fit/domain/auth/filter/JwtAuthenticationFilter.java
  src/main/java/eightplusone/bit/fit/domain/auth/interceptor/WebSocketInterceptor.java
  src/main/java/eightplusone/bit/fit/domain/chat/controller/ChatController.java
  src/main/java/eightplusone/bit/fit/domain/chat/dto/ChatMessageDto.java
  src/main/java/eightplusone/bit/fit/domain/chat/service/ChatService.java
  src/main/java/eightplusone/bit/fit/domain/session/controller/SessionWebSocketController.java
  src/main/java/eightplusone/bit/fit/domain/session/service/SessionService.java
  src/main/java/eightplusone/bit/fit/global/config/WebSocketConfig.java
  src/main/java/eightplusone/bit/fit/global/enums/ApiEndpoint.java
  src/test/java/eightplusone/bit/fit/domain/chat/service/ChatServiceTest.java
  src/test/java/eightplusone/bit/fit/domain/session/service/SessionServiceTest.java
Labels: 🎨refactor

#49 [#40] 미리담기 및 조회 기능
  src/main/java/eightplusone/bit/fit/domain/mysession/controller/MySessionController.java
  src/main/java/eightplusone/bit/fit/domain/mysession/dto/MySessionListResponseDto.java
  src/main/java/eightplusone/bit/fit/domain/mysession/dto/MySessionRegisterRequestDto.java
  src/main/java/eightplusone/bit/fit/domain/mysession/entity/MySession.java
  src/main/java/eightplusone/bit/fit/domain/mysession/enums/MySessionType.java
  src/main/java/eightplusone/bit/fit/domain/mysession/repository/MySessionRepository.java
  src/main/java/eightplusone/bit/fit/domain/mysession/service/MySessionService.java
  src/main/java/eightplusone/bit/fit/domain/session/entity/Session.java
  src/main/java/eightplusone/bit/fit/domain/user/entity/User.java
  src/main/java/eightplusone/bit/fit/global/enums/ApiEndpoint.java
  src/test/java/eightplusone/bit/fit/domain/mysession/service/MySessionServiceTest.java
  src/test/java/eightplusone/bit/fit/support/fixture/SessionFixture.java
Labels: ✨ feat

#51 [#50] top3 정렬 기능 오류 수정
  src/main/java/eightplusone/bit/fit/domain/auth/service/RedisTokenService.java
  src/main/java/eightplusone/bit/fit/domain/chat/dto/ChatMessageDto.java
  src/main/java/eightplusone/bit/fit/domain/chat/entity/ChatMessage.java
  src/main/java/eightplusone/bit/fit/domain/chat/repository/ChatRepository.java
  src/main/java/eightplusone/bit/fit/domain/chat/service/ChatService.java
  src/main/java/eightplusone/bit/fit/domain/user/repository/UserRedisRepository.java
  src/main/java/eightplusone/bit/fit/global/config/RedisConfig.java
  src/test/java/eightplusone/bit/fit/domain/chat/service/ChatServiceTest.java
Labels: ✨ feat, 🎨refactor, 🔨fix

#55 [#45] 관심 분야를 여러개 가지도록 수정
  src/main/java/eightplusone/bit/fit/domain/interest/entity/Interest.java
  src/main/java/eightplusone/bit/fit/domain/interest/entity/MyInterest.java
  src/main/java/eightplusone/bit/fit/domain/interest/repostiroy/InterestRepository.java
  src/main/java/eightplusone/bit/fit/domain/interest/repostiroy/MyInterestRepository.java
  src/main/java/eightplusone/bit/fit/domain/user/controller/UserController.java
  src/main/java/eightplusone/bit/fit/domain/user/dto/UserProfileResponseDto.java
  src/main/java/eightplusone/bit/fit/domain/user/dto/UserProfileUpdateRequestDto.java
  src/main/java/eightplusone/bit/fit/domain/user/entity/User.java
  src/main/java/eightplusone/bit/fit/domain/user/service/UserService.java
  src/test/java/eightplusone/bit/fit/domain/user/service/UserServiceTest.java
  src/test/java/eightplusone/bit/fit/support/fixture/InterestFixture.java
  src/test/java/eightplusone/bit/fit/support/fixture/UserFixture.java
Labels: ✨ feat

#56 [#35] cors 인증 헤더 값 상수로 수정
  src/main/java/eightplusone/bit/fit/global/config/SecurityConfig.java
  src/main/java/eightplusone/bit/fit/global/constants/CorsConstant.java
Labels: 🔨fix

#59 [#35] cors 인증 헤더 추가
  src/main/java/eightplusone/bit/fit/global/constants/CorsConstant.java
Labels: 🔨fix

#57 [#41] 강연 전체 조회 및 필터링 조회
  build.gradle
  src/main/java/eightplusone/bit/fit/domain/session/controller/EnterController.java
  src/main/java/eightplusone/bit/fit/domain/session/controller/SessionController.java
  src/main/java/eightplusone/bit/fit/domain/session/dto/SessionListResponseDto.java
  src/main/java/eightplusone/bit/fit/domain/session/repository/SessionRepository.java
  src/main/java/eightplusone/bit/fit/domain/session/service/SessionService.java
  src/main/java/eightplusone/bit/fit/domain/speaker/dto/SpeakerResponseDto.java
  src/main/java/eightplusone/bit/fit/domain/speaker/entity/Speaker.java
  src/main/java/eightplusone/bit/fit/domain/speaker/repository/SpeakerRepository.java
  src/main/java/eightplusone/bit/fit/domain/speaker/service/SpeakerService.java
  src/main/java/eightplusone/bit/fit/domain/tag/dto/TagResponseDto.java
  src/main/java/eightplusone/bit/fit/domain/tag/entity/Tag.java
  src/main/java/eightplusone/bit/fit/domain/tag/repository/TagRepository.java
  src/main/java/eightplusone/bit/fit/domain/tag/repository/TagRepositoryCustom.java
  src/main/java/eightplusone/bit/fit/domain/tag/repository/TagRepositoryImpl.java
  src/main/java/eightplusone/bit/fit/domain/tag/service/TagService.java
  src/main/java/eightplusone/bit/fit/global/config/QueryDslConfig.java
  src/main/java/eightplusone/bit/fit/global/enums/ApiEndpoint.java
  src/test/java/eightplusone/bit/fit/domain/session/service/SessionServiceTest.java
  src/test/java/eightplusone/bit/fit/support/fixture/SpeakerFixture.java
  src/test/java/eightplusone/bit/fit/support/fixture/TagFixture.java
Labels: ⚙ build, ✨ feat, 💡test

#62 [#53] TTL 수정
  src/main/java/eightplusone/bit/fit/domain/chat/controller/ChatController.java
  src/main/java/eightplusone/bit/fit/domain/chat/dto/ChatMessageDto.java
  src/main/java/eightplusone/bit/fit/domain/chat/entity/ChatMessage.java
  src/main/java/eightplusone/bit/fit/domain/chat/repository/ChatRepository.java
  src/main/java/eightplusone/bit/fit/domain/chat/service/ChatService.java
  src/main/java/eightplusone/bit/fit/domain/session/entity/Session.java
  src/test/java/eightplusone/bit/fit/domain/chat/repository/ChatRepositoryTest.java
  src/test/java/eightplusone/bit/fit/domain/chat/service/ChatServiceTest.java
Labels: ✨ feat, 🎨refactor, 🔨fix, 💡test

#67 [#66] QEntity 생성 경로 변경
  build.gradle
Labels: ⚙ build

#64 [#47] 좋아요 개수 실시간 업데이트
  src/main/java/eightplusone/bit/fit/domain/chat/dto/ChatMessageDto.java
  src/main/java/eightplusone/bit/fit/domain/chat/repository/ChatLikeRepository.java
  src/main/java/eightplusone/bit/fit/domain/chat/service/ChatService.java
  src/main/java/eightplusone/bit/fit/global/config/RedisConfig.java
  src/main/java/eightplusone/bit/fit/global/pubsub/LikeSubscriber.java
  src/test/java/eightplusone/bit/fit/domain/chat/repository/ChatLikeRepositoryTest.java
  src/test/java/eightplusone/bit/fit/domain/chat/service/ChatServiceTest.java
Labels: ✨ feat, 💡test

#70 [#69] 내 스케줄 응답 수정
  src/main/java/eightplusone/bit/fit/domain/mysession/dto/MySessionScheduleResponseDto.java
  src/main/java/eightplusone/bit/fit/domain/mysession/repository/MySessionRepository.java
  src/main/java/eightplusone/bit/fit/domain/mysession/service/MySessionService.java
  src/test/java/eightplusone/bit/fit/domain/mysession/service/MySessionServiceTest.java
Labels: ✨ feat, 💡test

#71 [#63] 좋아요 버튼 활성화를 위한 hasLiked API
  src/main/java/eightplusone/bit/fit/domain/chat/controller/ChatController.java
  src/main/java/eightplusone/bit/fit/domain/chat/repository/ChatLikeRepository.java
  src/main/java/eightplusone/bit/fit/domain/chat/service/ChatService.java
  src/test/java/eightplusone/bit/fit/domain/chat/repository/ChatLikeRepositoryTest.java
  src/test/java/eightplusone/bit/fit/domain/chat/service/ChatServiceTest.java
Labels: ✨ feat, 💡test

#74 [#73] 오디오 streaming 리팩토링
  .github/workflows/docker-deploy.yml
  src/main/java/eightplusone/bit/fit/domain/streaming/Room.java
  src/main/java/eightplusone/bit/fit/domain/streaming/RoomManager.java
  src/main/java/eightplusone/bit/fit/domain/streaming/controller/StreamingController.java
  src/main/java/eightplusone/bit/fit/domain/streaming/dto/IceCandidateDto.java
  src/main/java/eightplusone/bit/fit/domain/streaming/entity/AudioRoom.java
  src/main/java/eightplusone/bit/fit/domain/streaming/service/KurentoService.java
  src/main/java/eightplusone/bit/fit/domain/streaming/service/RoomService.java
  src/main/java/eightplusone/bit/fit/global/config/AudioWebSocketConfig.java
  src/main/java/eightplusone/bit/fit/global/config/WebSocketConfig.java
  src/main/java/eightplusone/bit/fit/global/websocket/CallHandler.java
  src/main/java/eightplusone/bit/fit/global/websocket/UserSession.java
Labels: 🎨refactor, ❌ remove

#77 [#75] 오디오 스트리밍 혼잡도 연결
  src/main/java/eightplusone/bit/fit/domain/session/entity/Session.java
  src/main/java/eightplusone/bit/fit/domain/session/repository/SessionRepository.java
  src/main/java/eightplusone/bit/fit/domain/session/service/SessionService.java
  src/main/java/eightplusone/bit/fit/domain/streaming/service/RoomService.java
  src/test/java/eightplusone/bit/fit/domain/session/service/SessionServiceTest.java
Labels: ✨ feat

#79 [#68] 강연 조회시 응답 dto 수정
  src/main/java/eightplusone/bit/fit/domain/auth/filter/JwtAuthenticationFilter.java
  src/main/java/eightplusone/bit/fit/domain/mysession/repository/MySessionRepository.java
  src/main/java/eightplusone/bit/fit/domain/session/dto/SessionListResponseDto.java
  src/main/java/eightplusone/bit/fit/domain/session/repository/SessionRepositoryCustom.java
  src/main/java/eightplusone/bit/fit/domain/session/repository/SessionRepositoryImpl.java
  src/main/java/eightplusone/bit/fit/domain/session/service/SessionService.java
  src/test/java/eightplusone/bit/fit/domain/session/service/SessionServiceTest.java
Labels: ✨ feat, 💡test

#72 [#48] 질문 페이징 기능 추가
  src/main/java/eightplusone/bit/fit/domain/chat/controller/ChatController.java
  src/main/java/eightplusone/bit/fit/domain/chat/service/ChatService.java
  src/test/java/eightplusone/bit/fit/domain/chat/service/ChatServiceTest.java
Labels: ✨ feat, 💡test

#82 [#42] S3 사진 업로드 삭제 기능 및 프로필 사진 기능
  build.gradle
  src/main/java/eightplusone/bit/fit/domain/image/dto/S3ImageDto.java
  src/main/java/eightplusone/bit/fit/domain/image/service/ImageService.java
  src/main/java/eightplusone/bit/fit/domain/user/controller/UserController.java
  src/main/java/eightplusone/bit/fit/domain/user/entity/User.java
  src/main/java/eightplusone/bit/fit/domain/user/service/UserService.java
Labels: ✨ feat

#84 chore: 계정 정보 조회 시 프로필 이미지도 함께 응답 #42
  src/main/java/eightplusone/bit/fit/domain/user/dto/UserAccountResponseDto.java
  src/main/java/eightplusone/bit/fit/domain/user/service/UserService.java
  src/test/java/eightplusone/bit/fit/domain/user/service/UserServiceTest.java
Labels: 🎨refactor

#83 [#81] 강연 상세보기 조회
  src/main/java/eightplusone/bit/fit/domain/mysession/repository/MySessionRepository.java
  src/main/java/eightplusone/bit/fit/domain/session/controller/SessionController.java
  src/main/java/eightplusone/bit/fit/domain/session/dto/SessionDetailResponseDto.java
  src/main/java/eightplusone/bit/fit/domain/session/repository/SessionRepository.java
  src/main/java/eightplusone/bit/fit/domain/session/repository/SessionRepositoryCustom.java
  src/main/java/eightplusone/bit/fit/domain/session/repository/SessionRepositoryImpl.java
  src/main/java/eightplusone/bit/fit/domain/session/service/SessionService.java
  src/main/java/eightplusone/bit/fit/global/exception/ErrorCode.java
  src/test/java/eightplusone/bit/fit/domain/session/service/SessionServiceTest.java
Labels: ✨ feat, 🎨refactor, 💡test, ✍️ comment

#87 [#85] Redis List -> ZSet 리팩터링
  src/main/java/eightplusone/bit/fit/domain/chat/controller/ChatController.java
  src/main/java/eightplusone/bit/fit/domain/chat/entity/ChatMessage.java
  src/main/java/eightplusone/bit/fit/domain/chat/repository/ChatLikeRepository.java
  src/main/java/eightplusone/bit/fit/domain/chat/service/ChatService.java
  src/test/java/eightplusone/bit/fit/domain/chat/repository/ChatLikeRepositoryTest.java
  src/test/java/eightplusone/bit/fit/domain/chat/repository/ChatRepositoryTest.java
  src/test/java/eightplusone/bit/fit/domain/chat/service/ChatServiceTest.java
Labels: 🎨refactor, 💡test

#90 [#88] Raw WebSocket 연결
  src/main/java/eightplusone/bit/fit/global/config/WebSocketConfig.java
Labels: 🔨fix

#89 [#37] 개인 정보에 이름 업데이트 추가
  src/main/java/eightplusone/bit/fit/domain/user/dto/UserProfileUpdateRequestDto.java
  src/main/java/eightplusone/bit/fit/domain/user/entity/User.java
  src/main/java/eightplusone/bit/fit/domain/user/service/UserService.java
  src/test/java/eightplusone/bit/fit/domain/user/service/UserServiceTest.java
Labels: 🎨refactor

#93 [#86] 추천 강연 리스트
  src/main/java/eightplusone/bit/fit/domain/auth/filter/JwtAuthenticationFilter.java
  src/main/java/eightplusone/bit/fit/domain/interest/mapper/InterestMapper.java
  src/main/java/eightplusone/bit/fit/domain/interest/repository/InterestRepository.java
  src/main/java/eightplusone/bit/fit/domain/interest/repository/MyInterestRepository.java
  src/main/java/eightplusone/bit/fit/domain/mysession/repository/MySessionRepository.java
  src/main/java/eightplusone/bit/fit/domain/session/controller/SessionController.java
  src/main/java/eightplusone/bit/fit/domain/session/dto/ScoredSession.java
  src/main/java/eightplusone/bit/fit/domain/session/repository/SessionRepositoryCustom.java
  src/main/java/eightplusone/bit/fit/domain/session/repository/SessionRepositoryImpl.java
  src/main/java/eightplusone/bit/fit/domain/session/service/SessionService.java
  src/main/java/eightplusone/bit/fit/domain/tag/entity/enums/CareerLevel.java
  src/main/java/eightplusone/bit/fit/domain/tag/repository/TagRepository.java
  src/main/java/eightplusone/bit/fit/domain/user/dto/UserProfileResponseDto.java
  src/main/java/eightplusone/bit/fit/domain/user/dto/UserProfileUpdateRequestDto.java
  src/main/java/eightplusone/bit/fit/domain/user/entity/User.java
  src/main/java/eightplusone/bit/fit/domain/user/entity/enums/YearLevel.java
  src/main/java/eightplusone/bit/fit/domain/user/service/UserService.java
  src/test/java/eightplusone/bit/fit/domain/session/service/SessionServiceTest.java
  src/test/java/eightplusone/bit/fit/domain/user/service/UserServiceTest.java
  src/test/java/eightplusone/bit/fit/support/fixture/UserFixture.java
Labels: ✨ feat, 🎨refactor, 💡test, 💡 rename, ✍️ comment

#98 [#97] 나의 세션 조회 시 강연자 정보 추가
  src/main/java/eightplusone/bit/fit/domain/mysession/dto/MySessionScheduleResponseDto.java
  src/main/java/eightplusone/bit/fit/domain/mysession/service/MySessionService.java
  src/main/java/eightplusone/bit/fit/domain/speaker/repository/SpeakerRepository.java
  src/test/java/eightplusone/bit/fit/domain/mysession/service/MySessionServiceTest.java
Labels: 🎨refactor

#102 [#100] 연사 정보 조회
  src/main/java/eightplusone/bit/fit/domain/speaker/controller/SpeakerController.java
  src/main/java/eightplusone/bit/fit/domain/speaker/dto/SpeakerListResponseDto.java
  src/main/java/eightplusone/bit/fit/domain/speaker/dto/SpeakerResponseDto.java
  src/main/java/eightplusone/bit/fit/domain/speaker/service/SpeakerService.java
  src/main/java/eightplusone/bit/fit/global/enums/ApiEndpoint.java
  src/test/java/eightplusone/bit/fit/domain/speaker/service/SpeakerServiceTest.java
Labels: ✨ feat, 💡test

#101 [#99] 채팅 리팩터링
  src/main/java/eightplusone/bit/fit/domain/auth/interceptor/WebSocketInterceptor.java
  src/main/java/eightplusone/bit/fit/domain/chat/controller/ChatController.java
  src/main/java/eightplusone/bit/fit/domain/chat/service/ChatService.java
  src/main/java/eightplusone/bit/fit/domain/user/repository/UserRepository.java
  src/test/java/eightplusone/bit/fit/domain/chat/service/ChatServiceTest.java
Labels: 🎨refactor, 💡test

#105 [#104] 채팅방 생성 api
  src/main/java/eightplusone/bit/fit/domain/chat/controller/ChatController.java
  src/main/java/eightplusone/bit/fit/domain/chat/repository/ChatRepository.java
  src/main/java/eightplusone/bit/fit/domain/chat/service/ChatService.java
  src/test/java/eightplusone/bit/fit/domain/chat/repository/ChatRepositoryTest.java
  src/test/java/eightplusone/bit/fit/domain/chat/service/ChatServiceTest.java
Labels: ✨ feat, 💡test

#103 [#96] 세션 리팩토링
  src/main/java/eightplusone/bit/fit/domain/session/controller/EnterController.java
  src/main/java/eightplusone/bit/fit/domain/session/controller/SessionController.java
  src/main/java/eightplusone/bit/fit/domain/session/dto/SessionDetailResponseDto.java
  src/main/java/eightplusone/bit/fit/domain/session/dto/SessionListResponseDto.java
  src/main/java/eightplusone/bit/fit/domain/session/service/SessionService.java
  src/main/java/eightplusone/bit/fit/domain/speaker/dto/SpeakerResponseDto.java
  src/main/java/eightplusone/bit/fit/domain/tag/dto/TagDto.java
  src/test/java/eightplusone/bit/fit/domain/session/service/SessionServiceIntegratedTest.java
  src/test/java/eightplusone/bit/fit/domain/session/service/SessionServiceTest.java
Labels: 🎨refactor, 💡test

#108 [#107] redis error 수정
  src/main/java/eightplusone/bit/fit/domain/chat/controller/ChatController.java
  src/main/java/eightplusone/bit/fit/domain/chat/repository/ChatRepository.java
  src/main/java/eightplusone/bit/fit/domain/chat/service/ChatService.java
  src/test/java/eightplusone/bit/fit/domain/chat/repository/ChatRepositoryTest.java
  src/test/java/eightplusone/bit/fit/domain/chat/service/ChatServiceTest.java
Labels: 🔨fix, 💡test

#109 [#54]좋아요 세션 조회 리스트에 강연자 정보 추가
  src/main/java/eightplusone/bit/fit/domain/mysession/dto/MySessionLikedSessionsResponseDto.java
  src/main/java/eightplusone/bit/fit/domain/mysession/service/MySessionService.java
  src/test/java/eightplusone/bit/fit/domain/mysession/service/MySessionServiceTest.java
Labels: 🎨refactor

#111 [#110] ChatSubscriber 수정
  src/main/java/eightplusone/bit/fit/global/pubsub/ChatSubscriber.java
Labels: 🔨fix

#115 [#113] 전체, 추천, 라이브 세션 조회 응답 isLive 추가
  src/main/java/eightplusone/bit/fit/domain/session/dto/SessionListResponseDto.java
  src/main/java/eightplusone/bit/fit/domain/user/dto/UserProfileResponseDto.java
  src/test/java/eightplusone/bit/fit/domain/session/service/SessionServiceTest.java
Labels: 🎨refactor

#114 [#112] timestamp 통일
  src/main/java/eightplusone/bit/fit/domain/chat/dto/ChatMessageDto.java
  src/main/java/eightplusone/bit/fit/domain/chat/entity/ChatMessage.java
  src/main/java/eightplusone/bit/fit/domain/chat/service/ChatService.java
  src/main/java/eightplusone/bit/fit/global/config/JacksonConfig.java
  src/main/java/eightplusone/bit/fit/global/config/RedisConfig.java
  src/test/java/eightplusone/bit/fit/domain/chat/repository/ChatRepositoryTest.java
  src/test/java/eightplusone/bit/fit/domain/chat/service/ChatServiceTest.java
Labels: 🔨fix, 💡test

#117 [#116] null 오류 해결
  src/main/java/eightplusone/bit/fit/domain/chat/service/ChatService.java
  src/main/java/eightplusone/bit/fit/global/config/RedisConfig.java
  src/main/java/eightplusone/bit/fit/global/pubsub/ChatSubscriber.java
  src/test/java/eightplusone/bit/fit/domain/chat/service/ChatServiceTest.java
Labels: 🔨fix, 💡test

#119 [#118] Redis에서 꺼낸 메시지 역직렬화 시 나노초 때문에 발생하던 오류 해결
  src/main/java/eightplusone/bit/fit/global/config/RedisConfig.java
Labels: 🔨fix

#121 [#120] 혼잡도 디버깅용 로그 추가
  src/main/java/eightplusone/bit/fit/domain/session/controller/SessionWebSocketController.java
  src/main/java/eightplusone/bit/fit/domain/session/service/SessionService.java
Labels: ✍️ comment

#123 [#122] getZSetSortedQuestions 메서드 에러 수정
  src/main/java/eightplusone/bit/fit/domain/chat/service/ChatService.java
  src/main/java/eightplusone/bit/fit/global/config/RedisConfig.java
  src/test/java/eightplusone/bit/fit/domain/chat/service/ChatServiceTest.java
Labels: 🔨fix, 💡test

#129 [#128] chat service 수정
  src/main/java/eightplusone/bit/fit/domain/chat/repository/ChatRepository.java
  src/main/java/eightplusone/bit/fit/domain/chat/service/ChatService.java
  src/test/java/eightplusone/bit/fit/domain/chat/service/ChatServiceTest.java
Labels: 🔨fix
